name: Helloworld Deployment

on:
  push:
    branches:
      - master

jobs:
  Build-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set Repository Name
        id: set-repository-name
        run: |
          echo "Setting Repository Name"
          repository_full_name="${{ toJSON(github.repository) }}"
          repository_name="${repository_full_name#*/}"
          echo "repository_name=${repository_name}" >> $GITHUB_ENV
          echo "Repository Name: $repository_name"
          echo "GitHub Run Number: ${{ github.run_number }}"
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          echo "Repository Name: $repository_name"
          docker build -t "${{ env.repository_name }}:${{ github.run_number }}" .







